apiVersion: v1
kind: Pod
metadata:
  name: high-priority-pod
  namespace: custom-scheduler-ns
  annotations:
    priority: "100"
spec:
  containers:
    - name: nginx
      image: nginx
  schedulerName: custom-scheduler
