apiVersion: v1
kind: Pod
metadata:
  name: low-priority-pod-1
  namespace: custom-scheduler-ns
  annotations:
    priority: "10"
spec:
  schedulerName: custom-scheduler
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: low-priority-pod-2
  namespace: custom-scheduler-ns
  annotations:
    priority: "10"
spec:
  schedulerName: custom-scheduler
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: low-priority-pod-3
  namespace: custom-scheduler-ns
  annotations:
    priority: "10"
spec:
  schedulerName: custom-scheduler
  containers:
    - name: nginx
      image: nginx
