apiVersion: v1
kind: Pod
metadata:
  name: default-scheduler-pod
  namespace: custom-scheduler-ns
spec:
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: custom-scheduler-pod
  namespace: custom-scheduler-ns
  annotations:
    priority: "50"
spec:
  schedulerName: custom-scheduler
  containers:
    - name: nginx
      image: nginx
